language: go

notifications:
  email: false

env:
  global:
    secure: j44ZcgOUJRrTpNsFME9w5CZCION0Psai6RaVQltqG2IokNb3SFdGrinDG+YTnChfAjL/w4Nv2OBxsb/sQtPIJpPXTpdraJo7gmcgRclbu4ezg0My6uE+T6bt0BG0vWYSTSWm59kFN6GQGTvJKCilgMi8+XP32/JQ12widiyQA/g=

install:
  - go get code.google.com/p/go.tools/cmd/goimports
  - go get code.google.com/p/go.tools/cmd/vet
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls

script:
  - wget https://gist.githubusercontent.com/mewmew/379014c9a2e6885e238d/raw/fb0c7d164113b1428f886dd470a613c74b9a9997/goclean.sh
  - chmod +x goclean.sh
  - ./goclean.sh
